const STATUS_VALIDATION_ERROR = 400;

const STATUS_INTERNAL_ERROR = 500;

const STATUS_SUCCESS = 200;

const STATUS_SUCCESS_CREATED = 201;

module.exports = {
  STATUS_VALIDATION_ERROR,
  STATUS_INTERNAL_ERROR,
  STATUS_SUCCESS,
  STATUS_SUCCESS_CREATED,
};
